export default {
  MANA: '[data-testid="mana-pool"]',
  CHANCES_CHECKBOX: '[data-testid="display-chance"]',
  DECK_CARD: '[data-testid*="deck-slot"]',
  CARD: '[data-testid="hand"] [data-testid="card"]',
  MANA_COST: '[data-testid="mana-value"]',
  CYCLE_BTN: '[data-testid="cycle-btn"]',
  PLAY_BTN: '[data-testid="play-btn"]',
  END_TURN_BTN: '[data-testid="end-turn-btn"]',
  CARD_LOG_IMAGE: '[data-testid="card-log-image"]',
  RESET_BTN: '[data-testid="reset-btn"]',
  RESET_CONFIRM_BTN: '[data-testid="reset-confirm-btn"]',
  EQUALS_MODE_CHECKBOX: '[data-testid="equals-mode"]',
  RESET_DIALOG: '#reset-dialog',
  BRAWL_MODIFIER_DIALOG: '#brawl-modifier-dialog',
  EQUALS_DIALOG: '#equals-mode-dialog',
  BRAWL_MODIFIER_SELECT: '[data-testid="brawl-modifier"]',
  HOS_FIRST_SUGGESTED: '#harvesters-dialog [data-testid="card-0"]',
  DECK_CARD_LEVEL: '[data-testid="deck-card-level"]',
  CARD_LOG: '[data-testid="card-log"]',
  RNG_INPUT: '[data-testid="RNG-input"]',
}
