import s from './selectors'

describe('Battle Simulator — Reset', () => {
  before(() => {
    cy.visit('/simulators/battle')
  })

  it('should reset all info', () => {
    cy.get(s.RED_HEALTH_INPUT).clear().type('9')
    cy.get(s.BLUE_FACTION_SELECT).select('ironclad')
    cy.get(s.GRID_MARKERS_CHECKBOX).click()
    cy.bsFill('A1', { card: 'Zhev' })
    cy.bsFill('E1', { card: 'Sound', level: 3, strength: 10, player: 'RED' })
    cy.bsDraw({ slot: 1, card: 'Toxic' })
    cy.bsDraw({ slot: 2, card: 'Crimson' })
    cy.bsDraw({ slot: 3, card: 'Copper' })
    cy.get(s.RESET_BOARD_BTN).click()
    cy.get(s.RESET_BOARD_CONFIRM_BTN).click()
    cy.get(s.RED_HEALTH).should('have.text', '10')
    cy.get(s.BLUE_FACTION).should('have.text', 'neutral')
    cy.get(s.GRID_MARKERS).should('not.exist')
    cy.get(s.CELL_A1).find(s.CELL_IMAGE).should('not.exist')
    cy.get(s.CELL_A1).find(s.CELL_STRENGTH).should('not.exist')
    cy.get(s.CELL_E1).find(s.CELL_IMAGE).should('not.exist')
    cy.get(s.CELL_E1).find(s.CELL_STRENGTH).should('not.exist')
    cy.get(s.CARD_SLOT_1)
      .find("[data-testid='card-slot-content']")
      .should('be.empty')
    cy.get(s.CARD_SLOT_2)
      .find("[data-testid='card-slot-content']")
      .should('be.empty')
    cy.get(s.CARD_SLOT_3)
      .find("[data-testid='card-slot-content']")
      .should('be.empty')
  })
})
