export const PROBABILITIES = {
  NO_MOVEMENT_RAVEN_TOKEN: 0.24,
  NO_MOVEMENT_TOAD_TOKEN: 0.64,
  DAWNSPARKS_STAYS: 0.71,
  DAWNSPARKS_HITS: 0.71,
  FROZEN_CORE_STAYS: 0.5,
  AHMI_RETURNS: 0.5,
}

export const HARVESTERS_OF_SOULS_RNG = {
  LEVEL_BONUS: {
    FRIENDLY: 2,
    REGULAR: 0,
    UNFRIENDLY: -3,
  },
  MAX_DEVIATION: 2,
}

export const FRIENDLY_CHANCES = {
  W9: PROBABILITIES.FROZEN_CORE_STAYS,
  S3: PROBABILITIES.AHMI_RETURNS,
  W16: PROBABILITIES.DAWNSPARKS_HITS * PROBABILITIES.DAWNSPARKS_STAYS,
}
