export const STATUSES = {
  PICKING_HAND: 'PICKING_HAND',
  PLAYING: 'PLAYING',
  PLAYING_FREEBOOTERS: 'PLAYING_FREEBOOTERS',
  PLAYING_SNAKE_EYES: 'PLAYING_SNAKE_EYES',
  PLAYING_GOLDGRUBBERS_REMOVING: 'PLAYING_GOLDGRUBBERS_REMOVING',
  PLAYING_GOLDGRUBBERS_DRAWING: 'PLAYING_GOLDGRUBBERS_DRAWING',
  PLAYING_FIRST_MUTINEER: 'PLAYING_FIRST_MUTINEER',
  PLAYING_QUEEN_OF_HERDS: 'PLAYING_QUEEN_OF_HERDS',
  PLAYING_ARCHDRUID_EARYN: 'PLAYING_ARCHDRUID_EARYN',
  CYCLING: 'CYCLING',
  REFILLING: 'REFILLING',
}
