export default {
  CARD: '.Card',
  CARD_ABILITY: '[data-testid="card-ability"]',
  CARD_RACE: '[data-testid="card-race"]',
  CARD_RARITY: '[data-testid="card-rarity"]',
  CARD_LEVEL: '[data-testid="card-level"]',

  LEVEL_SELECT: '[data-testid="level-select"]',
  FACTION_SELECT: '[data-testid="faction-select"]',
  TYPE_SELECT: '[data-testid="type-select"]',
  MANA_SELECT: '[data-testid="mana-select"]',
  MOVEMENT_SELECT: '[data-testid="movement-select"]',
  RARITY_SELECT: '[data-testid="rarity-select"]',
  RACE_SELECT: '[data-testid="race-select"]',
  ABILITY_SELECT: '[data-testid="ability-select"]',
  NAME_INPUT: '[data-testid="name-input"]',
  ELDER_CHECKBOX: '[data-testid="elder-checkbox"]',
  HERO_CHECKBOX: '[data-testid="hero-checkbox"]',
  RESET_FILTERS_BTN: '[data-testid="reset-filters-btn"]',

  RANDOM_BTN: '[data-testid="random-deck-btn"]',
  RANDOM_DIALOG: '#random-deck-dialog',
  RANDOM_FACTION_SELECT: '[data-testid="random-faction-select"]',
  RANDOM_MIN_FACTION_SELECT: '[data-testid="random-min-faction-select"]',
  RANDOM_MAX_EPIC_SELECT: '[data-testid="random-max-epic-select"]',
  RANDOM_MAX_LEGENDARY_SELECT: '[data-testid="random-max-legendary-select"]',
  RANDOM_DIALOG_CONFIRM: '[data-testid="random-deck-dialog-confirm-btn"]',
  DECK_CARD: '#deck .Deck__card',

  IMPORT_BTN: '[data-testid="import-btn"]',
  RESET_BTN: '[data-testid="reset-btn"]',
  RESET_CONFIRM_BTN: '[data-testid="reset-confirm-btn"]',
}
