export default {
  CARD: '.Card',
  CARD_ABILITY: '[data-testid="card-ability"]',
  CARD_RACE: '[data-testid="card-race"]',
  CARD_RARITY: '[data-testid="card-rarity"]',

  FACTION_SELECT: '[data-testid="faction-select"]',
  TYPE_SELECT: '[data-testid="type-select"]',
  MANA_SELECT: '[data-testid="mana-select"]',
  MOVEMENT_SELECT: '[data-testid="movement-select"]',
  RARITY_SELECT: '[data-testid="rarity-select"]',
  RACE_SELECT: '[data-testid="race-select"]',
  ABILITY_SELECT: '[data-testid="ability-select"]',
  NAME_INPUT: '[data-testid="name-input"]',
  ELDER_CHECKBOX: '[data-testid="elder-checkbox"]',
  HERO_CHECKBOX: '[data-testid="hero-checkbox"]',
  RESET_BTN: '[data-testid="reset-btn"]',

  DR_MANA: '[data-testid="mana-pool"]',
  DR_CHANCES_CHECKBOX: '[data-testid="display-chance"]',
  DR_DECK_CARD: '.Deck__card',
  DR_CARD: '[data-testid="hand"] [data-testid="card"]',
  DR_CYCLE_BTN: '[data-testid="cycle-btn"]',
  DR_PLAY_BTN: '[data-testid="play-btn"]',
  DR_END_TURN_BTN: '[data-testid="end-turn-btn"]',
}
