export default {
  CARD: '.Card',
  CARD_ABILITY: '[data-testid="card-ability"]',
  CARD_FACTION: '[data-testid="card-faction"]',
  CARD_IMAGE: '[data-testid="card-image"]',
  CARD_MANA: '[data-testid="card-mana"]',
  CARD_MOVEMENT: '[data-testid="card-movement"]',
  CARD_NAME: '[data-testid="card-name"]',
  CARD_PREVIEW: '[data-testid^="card-preview-"]',
  CARD_RACE: '[data-testid="card-race"]',
  CARD_RARITY: '[data-testid="card-rarity"]',
  CARD_STRENGTH: '[data-testid="card-strength"]',

  FACTION_SELECT: '[data-testid="faction-select"]',
  TYPE_SELECT: '[data-testid="type-select"]',
  MANA_SELECT: '[data-testid="mana-select"]',
  MOVEMENT_SELECT: '[data-testid="movement-select"]',
  RARITY_SELECT: '[data-testid="rarity-select"]',
  RACE_SELECT: '[data-testid="race-select"]',
  ABILITY_SELECT: '[data-testid="ability-select"]',
  NAME_INPUT: '[data-testid="name-input"]',
  ELDER_CHECKBOX: '[data-testid="elder-checkbox"]',
  HERO_CHECKBOX: '[data-testid="hero-checkbox"]',
}
