name: Revalidate
on:
  workflow_dispatch:
    inputs:
      path:
        description: 'The path to revalidate'
        required: true
        type: string

jobs:
  revalidate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17'

      - name: 'Revalidate ${{ github.event.inputs.path }}'
        run: node --experimental-fetch bin/revalidate.js "${{ github.event.inputs.path }}"
        env:
          NODE_ENV: production
          NEXT_REVALIDATION_TOKEN: ${{ secrets.NEXT_REVALIDATION_TOKEN }}
