name: Revalidate
on:
  workflow_dispatch:
    inputs:
      path:
        description: 'The path to revalidate'
        required: true
        type: string

jobs:
  revalidate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Revalidate path
        run: node -r esm bin/revalidate.js "${{ github.event.inputs.path }}"
        env:
          NODE_ENV: production
          NEXT_REVALIDATION_TOKEN: ${{ secrets.NEXT_REVALIDATION_TOKEN }}
